### Question 1 : 

Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [1]:
import numpy as np
## Checked Vandermode function from numpy documentation: https://numpy.org/doc/stable/reference/generated/numpy.vander.html
def vandermode_func(x,N):
    # x = input matrix should be given in list format. Ex: [1,2,3]
    # N = Determines how much the power should be raised
    return np.column_stack([np.array(x)**(N-1-i) for i in range(N)])

In [2]:
vandermode_func([1,2,3],4)

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1]], dtype=int32)

### Using numpy.vander function

In [3]:
# single line input array
x = np.array([1, 2, 3, 5])
# input vector
N = 3
#with increasing value as False
np.vander(x, N, increasing=False) 

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1]])

In [4]:
# single line input array
x = np.array([10, 20, 30, 40])
# input vector
N = 3
#with increasing value as True
print('Vandermonde Matrix is :\n','#'*40)
np.vander(x, N, increasing=True) 

Vandermonde Matrix is :
 ########################################


array([[   1,   10,  100],
       [   1,   20,  400],
       [   1,   30,  900],
       [   1,   40, 1600]])

In [5]:
### Numpy documentation for np.vander
import inspect
print(inspect.getsource(np.vander))

@array_function_dispatch(_vander_dispatcher)
def vander(x, N=None, increasing=False):
    """
    Generate a Vandermonde matrix.

    The columns of the output matrix are powers of the input vector. The
    order of the powers is determined by the `increasing` boolean argument.
    Specifically, when `increasing` is False, the `i`-th output column is
    the input vector raised element-wise to the power of ``N - i - 1``. Such
    a matrix with a geometric progression in each row is named for Alexandre-
    Theophile Vandermonde.

    Parameters
    ----------
    x : array_like
        1-D input array.
    N : int, optional
        Number of columns in the output.  If `N` is not specified, a square
        array is returned (``N = len(x)``).
    increasing : bool, optional
        Order of the powers of the columns.  If True, the powers increase
        from left to right, if False (the default) they are reversed.

        .. versionadded:: 1.9.0

    Returns
    -------
    out : ndar

## Question 2

Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:

The moving average sequence has n-k+1 elements as shown below.

The moving averages with k=4 of a ten-value sequence (n=10) is shown below

i 1 2 3 4 5 6 7 8 9 10

===== == == == == == == == == == ==

Input 10 20 30 40 50 60 70 80 90 100

y1 25 = (10+20+30+40)/4

y2 35 = (20+30+40+50)/4

y3 45 = (30+40+50+60)/4

y4 55 = (40+50+60+70)/4

y5 65 = (50+60+70+80)/4

y6 75 = (60+70+80+90)/4

y7 85 = (70+80+90+100)/4

Thus, the moving average sequence has n-k+1=10-4+1=7 values.

Question: Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [6]:
def moving_average(my_lst, k):
    sum_val = [0]
    moving_aver =[]
    for i, x in enumerate(my_lst, 1):
        sum_val.append(sum_val[i-1] + x) # summing up all the values and appending into sum_val list
        if i>=k:
            #Calculating the moving average  and appending into moving_aver for each iteration
            moving_aver.append(round(((sum_val[i] - sum_val[i-k])/k),2)) 
    print("Moving average values are: ", moving_aver,'\n')
    print("The moving average sequence has n-k+1:", len(moving_aver) ,' Values')

In [7]:
my_lst = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] 
k=3
moving_average(my_lst, k)

Moving average values are:  [5.0, 4.67, 5.67, 6.67, 9.67, 28.67, 49.33, 72.67, 84.0, 93.33, 116.33] 

The moving average sequence has n-k+1: 11  Values
